//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxApi {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Code {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Code() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WxApi.Code", typeof(Code).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 -2	 接口调用时，发生异常
        ///-1	 系统繁忙，此时请开发者稍候再试
        ///0	 请求成功
        ///40001	 获取access_token时AppSecret错误，或者access_token无效。请开发者认真比对AppSecret的正确性，或查看是否正在为恰当的公众号调用接口
        ///40002	 不合法的凭证类型
        ///40003	 不合法的OpenID，请开发者确认OpenID（该用户）是否已关注公众号，或是否是其他公众号的OpenID
        ///40004	 不合法的媒体文件类型
        ///40005	 不合法的文件类型
        ///40006	 不合法的文件大小
        ///40007	 不合法的媒体文件id
        ///40008	 不合法的消息类型
        ///40009	 不合法的图片文件大小
        ///40010	 不合法的语音文件大小
        ///40011	 不合法的视频文件大小
        ///40012	 不合法的缩略图文件大小
        ///40013	 不合法的AppID，请开发者检查AppID的正确性，避免异常字符，注意大小写
        ///40014	 不合法的access_token，请开发者认真比对access_token的有效性（如是否过期），或查看是否正在为恰当的公众号调用接口
        ///40015 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CodeInfo {
            get {
                return ResourceManager.GetString("CodeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮政EMS	Fsearch_code
        ///申通快递	002shentong
        ///中通速递	066zhongtong
        ///圆通速递	056yuantong
        ///天天快递	042tiantian
        ///顺丰速运	003shunfeng
        ///韵达快运	059Yunda
        ///宅急送	064zhaijisong
        ///汇通快运	020huitong
        ///易迅快递	zj001yixun 的本地化字符串。
        /// </summary>
        internal static string DeliveryCode {
            get {
                return ResourceManager.GetString("DeliveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;IT科技&quot;: {
        ///    &quot;互联网/电子商务&quot;: 1,
        ///    &quot;IT软件与服务&quot;: 2,
        ///    &quot;IT硬件与设备&quot;: 3,
        ///    &quot;电子技术&quot;: 4,
        ///    &quot;通信与运营商&quot;: 5,
        ///    &quot;网络游戏&quot;: 6
        ///  },
        ///  &quot;金融业&quot;: {
        ///    &quot;银行&quot;: 7,
        ///    &quot;基金|理财|信托&quot;: 8,
        ///    &quot;保险&quot;: 9
        ///  },
        ///  &quot;餐饮&quot;: {
        ///    &quot;餐饮&quot;: 10
        ///  },
        ///  &quot;酒店旅游&quot;: {
        ///    &quot;酒店&quot;: 11,
        ///    &quot;旅游&quot;: 12
        ///  },
        ///  &quot;运输与仓储&quot;: {
        ///    &quot;快递&quot;: 13,
        ///    &quot;物流&quot;: 14,
        ///    &quot;仓储&quot;: 15
        ///  },
        ///   &quot;教育&quot;: {
        ///    &quot;培训&quot;: 16,
        ///    &quot;院校&quot;: 17
        ///  },
        ///   &quot;政府与公共事业&quot;: {
        ///    &quot;学术科研&quot;: 18,
        ///    &quot;交警&quot;: 19,
        ///    &quot;博物馆&quot;: 20,
        ///    &quot;公共事业|非盈利机构&quot;: 21
        ///  },
        ///   &quot;医药护理&quot;: {
        ///    &quot;医药医疗&quot;: 22,
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IndustryCode {
            get {
                return ResourceManager.GetString("IndustryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{&quot;name&quot;:&quot;美食&quot;,&quot;value&quot;:&quot;&quot;,&quot;sub&quot;:[{&quot;name&quot;:&quot;江浙菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;粤菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;川菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;湘菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;东北菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;徽菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;闽菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;鲁菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;台湾菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;西北菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;东南亚菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;西餐&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;日韩菜&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quot;火锅&quot;,&quot;value&quot;:&quot;&quot;},{&quot;name&quot;:&quo... 的本地化字符串。
        /// </summary>
        internal static string StoreCategory {
            get {
                return ResourceManager.GetString("StoreCategory", resourceCulture);
            }
        }
    }
}
